from collections.abc import Iterator

import pytest
import responses
from helpers import params_of

from pyreinfolib import Client
from pyreinfolib.tiles import MAX_LATITUDE, Bounds, Tile, bounds, containing, count_covering, covering

BASE_URL = "https://www.reinfolib.mlit.go.jp/ex-api/external/"

# Tile coordinates lifted from the API manual's own examples, by way of the client tests.
# These are the only external check available on the grid convention, so they anchor
# everything else here.
REFERENCE_TILES = [
    Tile(z=11, x=1819, y=806),
    Tile(z=13, x=7312, y=3008),
]

# Spread across the country, including the ends of it, so the round trip is not only ever
# exercised near Tokyo.
JAPANESE_POINTS = [
    ("那覇", 127.6809, 26.2124),
    ("福岡", 130.4017, 33.5904),
    ("大阪", 135.5023, 34.6937),
    ("渋谷", 139.7016, 35.6580),
    ("仙台", 140.8694, 38.2682),
    ("札幌", 141.3545, 43.0618),
    ("稚内", 141.6739, 45.4156),
    ("南鳥島", 153.9807, 24.2867),
]

ZOOM_LEVELS = list(range(0, 21))


class TestContaining:
    @pytest.mark.parametrize("tile", REFERENCE_TILES, ids=lambda t: f"z{t.z}")
    def test_it_reproduces_the_tiles_used_in_the_api_manual(self, tile):
        """Asking for the centre of a known tile must give that tile back.

        This is the check that the grid convention matches the API's, rather than merely
        being self-consistent.
        """
        centre = bounds(tile)
        lon = (centre.west + centre.east) / 2
        lat = (centre.south + centre.north) / 2

        assert containing(lon=lon, lat=lat, z=tile.z) == tile

    def test_a_point_always_falls_inside_the_bounds_of_its_own_tile(self):
        """The round trip, over every zoom level the API offers and then some.

        Checked as a property rather than against fixed expectations, because a table of
        expected tile numbers would be generated by the same arithmetic it is meant to test.
        """
        for name, lon, lat in JAPANESE_POINTS:
            for z in ZOOM_LEVELS:
                tile = containing(lon=lon, lat=lat, z=z)
                extent = bounds(tile)

                assert extent.west <= lon <= extent.east, f"{name} lon at z={z}: {extent}"
                assert extent.south <= lat <= extent.north, f"{name} lat at z={z}: {extent}"

    def test_y_increases_southward(self):
        """XYZ, not TMS. Under TMS every tile in this library would be in the wrong hemisphere."""
        north = containing(lon=139.7, lat=43.06, z=13)
        south = containing(lon=139.7, lat=26.21, z=13)

        assert north.y < south.y

    def test_x_increases_eastward(self):
        west = containing(lon=127.68, lat=35.0, z=13)
        east = containing(lon=141.35, lat=35.0, z=13)

        assert west.x < east.x

    @pytest.mark.parametrize("z", ZOOM_LEVELS)
    def test_the_world_edges_do_not_fall_off_the_grid(self, z):
        """The south-east corner computes to index `n`, one past the last tile, before clamping."""
        last = 2**z - 1

        assert containing(lon=180.0, lat=-MAX_LATITUDE, z=z) == Tile(z, last, last)
        assert containing(lon=-180.0, lat=MAX_LATITUDE, z=z) == Tile(z, 0, 0)

    @pytest.mark.parametrize(
        ("lon", "lat"),
        [(139.7, 35.66), (127.68, 26.21), (-180.0, 0.0), (180.0, 0.0)],
    )
    def test_it_returns_a_tile_within_the_grid(self, lon, lat):
        z = 15
        tile = containing(lon=lon, lat=lat, z=z)

        assert 0 <= tile.x < 2**z
        assert 0 <= tile.y < 2**z


class TestContainingRejectsBadInput:
    @pytest.mark.parametrize("lat", [90.0, 86.0, -86.0, -90.0], ids=str)
    def test_latitudes_web_mercator_cannot_place(self, lat):
        with pytest.raises(ValueError, match="lat"):
            containing(lon=139.7, lat=lat, z=15)

    @pytest.mark.parametrize("lon", [180.1, 360.0, -180.1], ids=str)
    def test_longitudes_off_the_world(self, lon):
        with pytest.raises(ValueError, match="lon"):
            containing(lon=lon, lat=35.66, z=15)

    @pytest.mark.parametrize("name,lon,lat", JAPANESE_POINTS, ids=lambda v: v if isinstance(v, str) else "")
    def test_swapping_latitude_and_longitude_is_caught(self, name, lon, lat):
        """The reason the arguments are keyword only.

        Japan spans 122E to 154E, so a longitude handed over as a latitude is always past the
        Web Mercator limit. It fails loudly instead of quietly describing somewhere else.
        """
        with pytest.raises(ValueError, match="lat"):
            containing(lon=lat, lat=lon, z=15)

    @pytest.mark.parametrize("z", [-1, -15])
    def test_negative_zoom(self, z):
        with pytest.raises(ValueError, match="z"):
            containing(lon=139.7, lat=35.66, z=z)


class TestBounds:
    def test_zoom_zero_is_the_whole_projected_world(self):
        extent = bounds(Tile(z=0, x=0, y=0))

        assert extent.west == pytest.approx(-180.0)
        assert extent.east == pytest.approx(180.0)
        assert extent.north == pytest.approx(MAX_LATITUDE)
        assert extent.south == pytest.approx(-MAX_LATITUDE)

    def test_adjacent_tiles_share_an_edge(self):
        """Gaps or overlaps here would make `covering` miss or duplicate data."""
        left = bounds(Tile(z=15, x=29099, y=12905))
        right = bounds(Tile(z=15, x=29100, y=12905))
        below = bounds(Tile(z=15, x=29099, y=12906))

        assert left.east == pytest.approx(right.west)
        assert left.south == pytest.approx(below.north)

    def test_it_returns_a_named_tuple_in_geojson_bbox_order(self):
        extent = bounds(Tile(z=13, x=7312, y=3008))

        assert isinstance(extent, Bounds)
        assert tuple(extent) == (extent.west, extent.south, extent.east, extent.north)
        assert extent.west < extent.east
        assert extent.south < extent.north


class TestCovering:
    def test_it_is_lazy(self):
        """A prefecture at zoom 15 runs to thousands of tiles, so building a list up front
        would commit the caller to the whole thing before the first request.
        """
        result = covering(west=138.94, south=35.5, east=139.93, north=35.9, z=15)

        assert isinstance(result, Iterator)
        assert not isinstance(result, list)

    def test_a_box_inside_one_tile_yields_that_tile_only(self):
        tile = Tile(z=13, x=7312, y=3008)
        extent = bounds(tile)
        inset_lon = (extent.east - extent.west) / 4
        inset_lat = (extent.north - extent.south) / 4

        result = list(
            covering(
                west=extent.west + inset_lon,
                south=extent.south + inset_lat,
                east=extent.east - inset_lon,
                north=extent.north - inset_lat,
                z=tile.z,
            )
        )

        assert result == [tile]

    def test_it_yields_row_by_row_from_the_north_west(self):
        result = list(covering(west=139.665, south=35.640, east=139.724, north=35.679, z=13))
        first, last = result[0], result[-1]

        assert first.x <= last.x
        assert first.y <= last.y
        # Row major: y is non-decreasing throughout, and x restarts on each new row.
        assert [t.y for t in result] == sorted(t.y for t in result)
        assert result == sorted(result, key=lambda t: (t.y, t.x))

    def test_every_tile_it_yields_overlaps_the_box(self):
        west, south, east, north = 139.665, 35.640, 139.724, 35.679

        for tile in covering(west=west, south=south, east=east, north=north, z=14):
            extent = bounds(tile)

            assert extent.west < east and extent.east > west, f"{tile} is outside in longitude"
            assert extent.south < north and extent.north > south, f"{tile} is outside in latitude"

    def test_the_box_corners_are_covered(self):
        """Missing a corner tile would silently drop data at the edge of an area of interest."""
        west, south, east, north = 139.665, 35.640, 139.724, 35.679
        result = set(covering(west=west, south=south, east=east, north=north, z=15))

        for lon, lat in [(west, north), (east, north), (west, south), (east, south)]:
            assert containing(lon=lon, lat=lat, z=15) in result

    @pytest.mark.parametrize("z", [11, 12, 13, 14, 15])
    def test_count_covering_agrees_with_what_covering_yields(self, z):
        box = {"west": 139.562, "south": 35.520, "east": 139.920, "north": 35.818}

        assert count_covering(**box, z=z) == len(list(covering(**box, z=z)))

    @pytest.mark.parametrize("call", [covering, count_covering], ids=["covering", "count_covering"])
    def test_an_inverted_box_is_rejected(self, call):
        """Silently swapping the edges would hide a caller's mistake behind plausible data."""
        with pytest.raises(ValueError, match="west"):
            list(call(west=139.9, south=35.5, east=139.5, north=35.9, z=13))

        with pytest.raises(ValueError, match="south"):
            list(call(west=139.5, south=35.9, east=139.9, north=35.5, z=13))


class TestTile:
    def test_it_unpacks_into_the_clients_tile_methods(self):
        """The field order is a contract with `Client`, not a detail.

        `client.get_...(*tile)` is the documented way to use this, so reordering the fields
        would break callers while every other test here kept passing.
        """
        tile = containing(lon=139.7016, lat=35.6580, z=15)

        with responses.RequestsMock() as mock_api:
            mock_api.get(f"{BASE_URL}XKT015", json={"type": "FeatureCollection", "features": []})

            with Client(api_key="dummy") as client:
                client.get_number_of_passengers_per_station(*tile)

            params = params_of(mock_api.calls[0].request)

        assert params["z"] == str(tile.z)
        assert params["x"] == str(tile.x)
        assert params["y"] == str(tile.y)
